apiVersion: v1
kind: ServiceAccount
metadata:
  name: capture
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capture
rules:
   - apiGroups: [""]
     resources: ["pods"]
     verbs:
     - get
     - list
     - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: capture
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capture
subjects:
  - kind: ServiceAccount
    name: capture
    namespace: default

